### PR TITLE
Pin winnow >= 0.6.26 (ModalResult added in 0.6.26)

### LINKED ISSUE #29: v0.4.0 fails to compile: winnow::ModalResult not found
## Problem

`graphs-tui` v0.4.0 fails to compile with 5 errors — all `unresolved import winnow::ModalResult`:

```
error[E0432]: unresolved import `winnow::ModalResult`
  --> d2_parser.rs:20:5
error[E0432]: unresolved import `winnow::ModalResult`
  --> parser.rs:5:5
error[E0432]: unresolved import `winnow::ModalResult`
  --> pie_parser.rs:9:5
error[E0432]: unresolved import `winnow::ModalResult`
  --> seq_parser.rs:10:5
error[E0432]: unresolved import `winnow::ModalResult`
  --> state_parser.rs:8:5
```

`winnow::ModalResult` was likely renamed or moved in a newer winnow version. The Cargo.toml probably needs a version pin or the import paths need updating.

## Reproduce

```sh
cargo add graphs-tui@0.4.0
cargo check
```

## Workaround

Use v0.3.2 which compiles fine.

### PR DESCRIPTION
**Pull request by onnimonni**
## Summary
- `ModalResult` was added in winnow 0.6.26, but Cargo.toml specified `"0.6"` allowing older versions
- Fix: one-line pin `winnow = "0.6.26"`

Fixes #29

## Test plan
- `rm Cargo.lock && cargo test` — all 218 tests pass

### CODE REVIEW

**Comment by onnimonni** [comment]
## Review

**1. Misleading title** — Says "require 0.6.26+" but code does the opposite: downgrades to `PResult` (deprecated in 0.6.25+) so it works on ALL 0.6.x.

**2. `#![allow(deprecated)]` is too broad** — Silences ALL deprecation warnings crate-wide, not just `PResult`.

**3. Cargo.toml not changed** — Root cause is `winnow = "0.6"` allowing 0.6.0–0.6.24 which lack `ModalResult`. Simpler fix: one-line pin in Cargo.toml:
```toml
winnow = "0.6.26"
```

No code changes needed. The `kdl =0.6.24` workspace conflict from the commit msg is a `kdl` problem (exact pins are hostile to dependents), not ours to work around by downgrading API.

Closing in favor of a minimal Cargo.toml fix.

**Comment by onnimonni** [comment]
Updated — minimal one-line Cargo.toml fix only. No code changes, no `#![allow(deprecated)]`.

**Comment by onnimonni** [comment]
Updated approach after learning kdl pins `winnow =0.6.24`:

Instead of pinning `winnow = "0.6.26"`, replaced `ModalResult` (0.6.25+) and `ErrMode::from_input` (0.6.25+) with APIs that work across all 0.6.x:

- `ModalResult<T>` → local `type WResult<O> = Result<O, ErrMode<ContextError>>` (same underlying type, no deprecated imports)
- `ErrMode::from_input(input)` → `ErrMode::Backtrack(ContextError::new())`
- Added `minimal-versions` CI job to catch this class of issue going forward
